POST http://localhost:8080/translate/withTarget?text=mouse&target=az

### 
GET http://localhost:8080/all

###
GET http://localhost:8080/get/paper

###
POST http://localhost:8080/translate?text=cut

###
POST http://localhost:8080/translate/withSource?source=en&text=line&target=az

###
GET http://localhost:8080/getSour/en

###
GET http://localhost:8080/getTarg/ru

###
GET http://localhost:8080/get/sourceLang/targetLang?source=en&target=fr

###
DELETE http://localhost:8080/delete/if

###
POST  http://localhost:8080/save
Content-Type:  application/json 

{
    "sourceLang":"en",
    "targetLang":"az",
    "sourceText":"paper",
    "translatedText": "kagiz"

}

###
PUT http://localhost:8080/update/8
Content-Type: application/json

{
    "sourceLang":"en",
    "targetLang":"az",
    "sourceText":"i went home",
    "translatedText": "men eve getdim"
}


