POST http://localhost:8080/translate/withTarget?text=mouse&target=az

### 
GET http://localhost:8080/dictionary/all

###
GET http://localhost:8080/dictionary/get/bed

###
POST http://localhost:8080/dictionary/translate?text=black

###
POST http://localhost:8080/translate/withSource?source=en&text=line&target=az

###
GET http://localhost:8080/getSour/en?username=qismet&password=qismet123

###
GET http://localhost:8080/dictionary/getTarg/ru

###
GET http://localhost:8080/get/sourceLang/targetLang?source=en&target=fr

###
DELETE http://localhost:8080/dictionary/delete/if

###
POST  http://localhost:8080/save
Content-Type:  application/json 

{
    "sourceLang":"en",
    "targetLang":"az",
    "sourceText":"paper",
    "translatedText": "kagiz"

}

###
PUT http://localhost:8080/update/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJRaXNtZXQiLCJpYXQiOjE3MDI1OTY2OTAsImV4cCI6MTcwMjU5Njc5MH0.0y10hHC7gIzpWXFzW_j5KUe5RAE2cZNhXu2qdnx9tnc

{
    "sourceLang":"en",
    "targetLang":"az",
    "sourceText":"i went home",
    "translatedText": "men eve getdim"
}


###
POST http://localhost:8080/auth/register
Content-Type:  application/json

{
    "firstname":"Qismet",
    "lastname": "Kamilov",
    "mail":"qismet600@gmail.com",
    "password": "qismet123",
    "role":"Admin"
}

###
POST http://localhost:8080/auth/login
Content-Type: application/json

{
    "mail":"qismet600@gmail.com",
    "password": "qismet123"   
}